version: "3.6"

services:
    emailqueue:
        image: emailqueue-apache
        container_name: emailqueue-apache
        build:
            context: .
            dockerfile: ./apache/Dockerfile
        ports:
            - 8081:80
            - 443:443
        networks:
            - emailqueue
        volumes:
            - ../application.config.inc.php:/var/www/BIRTHDAY_GOLD/emailqueue/config/application.config.inc.php
            - /var/web_certs/BIRTHDAY_SERVER/birthday.gold:/etc/ssl/private:ro
        restart: unless-stopped

    emailqueue-mysql:
        image: mysql:8.0
        container_name: emailqueue-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=change_this_password
            - MYSQL_DATABASE=emailqueue
        ports:
            - 3307:3306
        networks:
            - emailqueue
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/emailqueue_init.sql:/docker-entrypoint-initdb.d/schema.sql:ro
        restart: unless-stopped

volumes:
    emailqueue-db-data: {}

networks:
    emailqueue:
        name: emailqueue
